/**
 * eventmobi
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: api-v2
 * Contact: support@cloud-elements.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Eventmobi);
  }
}(this, function(expect, Eventmobi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Eventmobi.CustomFieldsNames();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CustomFieldsNames', function() {
    it('should create an instance of CustomFieldsNames', function() {
      // uncomment below and update the code to test CustomFieldsNames
      //var instane = new Eventmobi.CustomFieldsNames();
      //expect(instance).to.be.a(Eventmobi.CustomFieldsNames);
    });

    it('should have the property typeName (base name: "type_name")', function() {
      // uncomment below and update the code to test the property typeName
      //var instane = new Eventmobi.CustomFieldsNames();
      //expect(instance).to.be();
    });

    it('should have the property eventId (base name: "event_id")', function() {
      // uncomment below and update the code to test the property eventId
      //var instane = new Eventmobi.CustomFieldsNames();
      //expect(instance).to.be();
    });

    it('should have the property deleted (base name: "deleted")', function() {
      // uncomment below and update the code to test the property deleted
      //var instane = new Eventmobi.CustomFieldsNames();
      //expect(instance).to.be();
    });

    it('should have the property sectionId (base name: "section_id")', function() {
      // uncomment below and update the code to test the property sectionId
      //var instane = new Eventmobi.CustomFieldsNames();
      //expect(instance).to.be();
    });

    it('should have the property visibility (base name: "visibility")', function() {
      // uncomment below and update the code to test the property visibility
      //var instane = new Eventmobi.CustomFieldsNames();
      //expect(instance).to.be();
    });

    it('should have the property typeId (base name: "type_id")', function() {
      // uncomment below and update the code to test the property typeId
      //var instane = new Eventmobi.CustomFieldsNames();
      //expect(instance).to.be();
    });

    it('should have the property editPermissions (base name: "edit_permissions")', function() {
      // uncomment below and update the code to test the property editPermissions
      //var instane = new Eventmobi.CustomFieldsNames();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new Eventmobi.CustomFieldsNames();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new Eventmobi.CustomFieldsNames();
      //expect(instance).to.be();
    });

    it('should have the property position (base name: "position")', function() {
      // uncomment below and update the code to test the property position
      //var instane = new Eventmobi.CustomFieldsNames();
      //expect(instance).to.be();
    });

    it('should have the property validationId (base name: "validation_id")', function() {
      // uncomment below and update the code to test the property validationId
      //var instane = new Eventmobi.CustomFieldsNames();
      //expect(instance).to.be();
    });

  });

}));
