/**
 * eventmobi
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: api-v2
 * Contact: support@cloud-elements.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * Ads
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-08-25T16:18:19.244-04:00")
public class Ads   {
  @SerializedName("sponsorshiplevel")
  private String sponsorshiplevel = null;

  @SerializedName("logo_name")
  private String logoName = null;

  @SerializedName("call_to_action")
  private String callToAction = null;

  @SerializedName("exhibitor_id")
  private String exhibitorId = null;

  @SerializedName("link")
  private String link = null;

  @SerializedName("rich")
  private String rich = null;

  @SerializedName("exhibitor_name")
  private String exhibitorName = null;

  @SerializedName("title")
  private String title = null;

  @SerializedName("message")
  private String message = null;

  @SerializedName("type")
  private String type = null;

  @SerializedName("call_to_action_url")
  private String callToActionUrl = null;

  @SerializedName("filename")
  private String filename = null;

  @SerializedName("background_color")
  private String backgroundColor = null;

  @SerializedName("call_to_action_text")
  private String callToActionText = null;

  @SerializedName("id")
  private String id = null;

  public Ads sponsorshiplevel(String sponsorshiplevel) {
    this.sponsorshiplevel = sponsorshiplevel;
    return this;
  }

   /**
   * Get sponsorshiplevel
   * @return sponsorshiplevel
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSponsorshiplevel() {
    return sponsorshiplevel;
  }

  public void setSponsorshiplevel(String sponsorshiplevel) {
    this.sponsorshiplevel = sponsorshiplevel;
  }

  public Ads logoName(String logoName) {
    this.logoName = logoName;
    return this;
  }

   /**
   * Get logoName
   * @return logoName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getLogoName() {
    return logoName;
  }

  public void setLogoName(String logoName) {
    this.logoName = logoName;
  }

  public Ads callToAction(String callToAction) {
    this.callToAction = callToAction;
    return this;
  }

   /**
   * Get callToAction
   * @return callToAction
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCallToAction() {
    return callToAction;
  }

  public void setCallToAction(String callToAction) {
    this.callToAction = callToAction;
  }

  public Ads exhibitorId(String exhibitorId) {
    this.exhibitorId = exhibitorId;
    return this;
  }

   /**
   * Get exhibitorId
   * @return exhibitorId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getExhibitorId() {
    return exhibitorId;
  }

  public void setExhibitorId(String exhibitorId) {
    this.exhibitorId = exhibitorId;
  }

  public Ads link(String link) {
    this.link = link;
    return this;
  }

   /**
   * Get link
   * @return link
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getLink() {
    return link;
  }

  public void setLink(String link) {
    this.link = link;
  }

  public Ads rich(String rich) {
    this.rich = rich;
    return this;
  }

   /**
   * Get rich
   * @return rich
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getRich() {
    return rich;
  }

  public void setRich(String rich) {
    this.rich = rich;
  }

  public Ads exhibitorName(String exhibitorName) {
    this.exhibitorName = exhibitorName;
    return this;
  }

   /**
   * Get exhibitorName
   * @return exhibitorName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getExhibitorName() {
    return exhibitorName;
  }

  public void setExhibitorName(String exhibitorName) {
    this.exhibitorName = exhibitorName;
  }

  public Ads title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public Ads message(String message) {
    this.message = message;
    return this;
  }

   /**
   * Get message
   * @return message
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public Ads type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public Ads callToActionUrl(String callToActionUrl) {
    this.callToActionUrl = callToActionUrl;
    return this;
  }

   /**
   * Get callToActionUrl
   * @return callToActionUrl
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCallToActionUrl() {
    return callToActionUrl;
  }

  public void setCallToActionUrl(String callToActionUrl) {
    this.callToActionUrl = callToActionUrl;
  }

  public Ads filename(String filename) {
    this.filename = filename;
    return this;
  }

   /**
   * Get filename
   * @return filename
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getFilename() {
    return filename;
  }

  public void setFilename(String filename) {
    this.filename = filename;
  }

  public Ads backgroundColor(String backgroundColor) {
    this.backgroundColor = backgroundColor;
    return this;
  }

   /**
   * Get backgroundColor
   * @return backgroundColor
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getBackgroundColor() {
    return backgroundColor;
  }

  public void setBackgroundColor(String backgroundColor) {
    this.backgroundColor = backgroundColor;
  }

  public Ads callToActionText(String callToActionText) {
    this.callToActionText = callToActionText;
    return this;
  }

   /**
   * Get callToActionText
   * @return callToActionText
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCallToActionText() {
    return callToActionText;
  }

  public void setCallToActionText(String callToActionText) {
    this.callToActionText = callToActionText;
  }

  public Ads id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Ads ads = (Ads) o;
    return Objects.equals(this.sponsorshiplevel, ads.sponsorshiplevel) &&
        Objects.equals(this.logoName, ads.logoName) &&
        Objects.equals(this.callToAction, ads.callToAction) &&
        Objects.equals(this.exhibitorId, ads.exhibitorId) &&
        Objects.equals(this.link, ads.link) &&
        Objects.equals(this.rich, ads.rich) &&
        Objects.equals(this.exhibitorName, ads.exhibitorName) &&
        Objects.equals(this.title, ads.title) &&
        Objects.equals(this.message, ads.message) &&
        Objects.equals(this.type, ads.type) &&
        Objects.equals(this.callToActionUrl, ads.callToActionUrl) &&
        Objects.equals(this.filename, ads.filename) &&
        Objects.equals(this.backgroundColor, ads.backgroundColor) &&
        Objects.equals(this.callToActionText, ads.callToActionText) &&
        Objects.equals(this.id, ads.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sponsorshiplevel, logoName, callToAction, exhibitorId, link, rich, exhibitorName, title, message, type, callToActionUrl, filename, backgroundColor, callToActionText, id);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Ads {\n");
    
    sb.append("    sponsorshiplevel: ").append(toIndentedString(sponsorshiplevel)).append("\n");
    sb.append("    logoName: ").append(toIndentedString(logoName)).append("\n");
    sb.append("    callToAction: ").append(toIndentedString(callToAction)).append("\n");
    sb.append("    exhibitorId: ").append(toIndentedString(exhibitorId)).append("\n");
    sb.append("    link: ").append(toIndentedString(link)).append("\n");
    sb.append("    rich: ").append(toIndentedString(rich)).append("\n");
    sb.append("    exhibitorName: ").append(toIndentedString(exhibitorName)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    callToActionUrl: ").append(toIndentedString(callToActionUrl)).append("\n");
    sb.append("    filename: ").append(toIndentedString(filename)).append("\n");
    sb.append("    backgroundColor: ").append(toIndentedString(backgroundColor)).append("\n");
    sb.append("    callToActionText: ").append(toIndentedString(callToActionText)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

