/**
 * eventmobi
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: api-v2
 * Contact: support@cloud-elements.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * Config
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-08-25T16:18:19.244-04:00")
public class Config   {
  @SerializedName("hide_regular_fields")
  private Boolean hideRegularFields = null;

  @SerializedName("custom_fields_enabled")
  private Boolean customFieldsEnabled = null;

  public Config hideRegularFields(Boolean hideRegularFields) {
    this.hideRegularFields = hideRegularFields;
    return this;
  }

   /**
   * Get hideRegularFields
   * @return hideRegularFields
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getHideRegularFields() {
    return hideRegularFields;
  }

  public void setHideRegularFields(Boolean hideRegularFields) {
    this.hideRegularFields = hideRegularFields;
  }

  public Config customFieldsEnabled(Boolean customFieldsEnabled) {
    this.customFieldsEnabled = customFieldsEnabled;
    return this;
  }

   /**
   * Get customFieldsEnabled
   * @return customFieldsEnabled
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getCustomFieldsEnabled() {
    return customFieldsEnabled;
  }

  public void setCustomFieldsEnabled(Boolean customFieldsEnabled) {
    this.customFieldsEnabled = customFieldsEnabled;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Config config = (Config) o;
    return Objects.equals(this.hideRegularFields, config.hideRegularFields) &&
        Objects.equals(this.customFieldsEnabled, config.customFieldsEnabled);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hideRegularFields, customFieldsEnabled);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Config {\n");
    
    sb.append("    hideRegularFields: ").append(toIndentedString(hideRegularFields)).append("\n");
    sb.append("    customFieldsEnabled: ").append(toIndentedString(customFieldsEnabled)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

