/**
 * eventmobi
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: api-v2
 * Contact: support@cloud-elements.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * CustomFieldsNames
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-08-26T15:51:37.800-04:00")
public class CustomFieldsNames   {
  @SerializedName("type_name")
  private String typeName = null;

  @SerializedName("event_id")
  private String eventId = null;

  @SerializedName("deleted")
  private String deleted = null;

  @SerializedName("section_id")
  private String sectionId = null;

  @SerializedName("visibility")
  private String visibility = null;

  @SerializedName("type_id")
  private String typeId = null;

  @SerializedName("edit_permissions")
  private String editPermissions = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("position")
  private String position = null;

  @SerializedName("validation_id")
  private String validationId = null;

  public CustomFieldsNames typeName(String typeName) {
    this.typeName = typeName;
    return this;
  }

   /**
   * Get typeName
   * @return typeName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTypeName() {
    return typeName;
  }

  public void setTypeName(String typeName) {
    this.typeName = typeName;
  }

  public CustomFieldsNames eventId(String eventId) {
    this.eventId = eventId;
    return this;
  }

   /**
   * Get eventId
   * @return eventId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getEventId() {
    return eventId;
  }

  public void setEventId(String eventId) {
    this.eventId = eventId;
  }

  public CustomFieldsNames deleted(String deleted) {
    this.deleted = deleted;
    return this;
  }

   /**
   * Get deleted
   * @return deleted
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDeleted() {
    return deleted;
  }

  public void setDeleted(String deleted) {
    this.deleted = deleted;
  }

  public CustomFieldsNames sectionId(String sectionId) {
    this.sectionId = sectionId;
    return this;
  }

   /**
   * Get sectionId
   * @return sectionId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSectionId() {
    return sectionId;
  }

  public void setSectionId(String sectionId) {
    this.sectionId = sectionId;
  }

  public CustomFieldsNames visibility(String visibility) {
    this.visibility = visibility;
    return this;
  }

   /**
   * Get visibility
   * @return visibility
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getVisibility() {
    return visibility;
  }

  public void setVisibility(String visibility) {
    this.visibility = visibility;
  }

  public CustomFieldsNames typeId(String typeId) {
    this.typeId = typeId;
    return this;
  }

   /**
   * Get typeId
   * @return typeId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTypeId() {
    return typeId;
  }

  public void setTypeId(String typeId) {
    this.typeId = typeId;
  }

  public CustomFieldsNames editPermissions(String editPermissions) {
    this.editPermissions = editPermissions;
    return this;
  }

   /**
   * Get editPermissions
   * @return editPermissions
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getEditPermissions() {
    return editPermissions;
  }

  public void setEditPermissions(String editPermissions) {
    this.editPermissions = editPermissions;
  }

  public CustomFieldsNames name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CustomFieldsNames id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public CustomFieldsNames position(String position) {
    this.position = position;
    return this;
  }

   /**
   * Get position
   * @return position
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPosition() {
    return position;
  }

  public void setPosition(String position) {
    this.position = position;
  }

  public CustomFieldsNames validationId(String validationId) {
    this.validationId = validationId;
    return this;
  }

   /**
   * Get validationId
   * @return validationId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getValidationId() {
    return validationId;
  }

  public void setValidationId(String validationId) {
    this.validationId = validationId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomFieldsNames customFieldsNames = (CustomFieldsNames) o;
    return Objects.equals(this.typeName, customFieldsNames.typeName) &&
        Objects.equals(this.eventId, customFieldsNames.eventId) &&
        Objects.equals(this.deleted, customFieldsNames.deleted) &&
        Objects.equals(this.sectionId, customFieldsNames.sectionId) &&
        Objects.equals(this.visibility, customFieldsNames.visibility) &&
        Objects.equals(this.typeId, customFieldsNames.typeId) &&
        Objects.equals(this.editPermissions, customFieldsNames.editPermissions) &&
        Objects.equals(this.name, customFieldsNames.name) &&
        Objects.equals(this.id, customFieldsNames.id) &&
        Objects.equals(this.position, customFieldsNames.position) &&
        Objects.equals(this.validationId, customFieldsNames.validationId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(typeName, eventId, deleted, sectionId, visibility, typeId, editPermissions, name, id, position, validationId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomFieldsNames {\n");
    
    sb.append("    typeName: ").append(toIndentedString(typeName)).append("\n");
    sb.append("    eventId: ").append(toIndentedString(eventId)).append("\n");
    sb.append("    deleted: ").append(toIndentedString(deleted)).append("\n");
    sb.append("    sectionId: ").append(toIndentedString(sectionId)).append("\n");
    sb.append("    visibility: ").append(toIndentedString(visibility)).append("\n");
    sb.append("    typeId: ").append(toIndentedString(typeId)).append("\n");
    sb.append("    editPermissions: ").append(toIndentedString(editPermissions)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    position: ").append(toIndentedString(position)).append("\n");
    sb.append("    validationId: ").append(toIndentedString(validationId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

