/**
 * eventmobi
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: api-v2
 * Contact: support@cloud-elements.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Config;
import io.swagger.client.model.CustomFieldsNames;
import io.swagger.client.model.Items;
import java.util.ArrayList;
import java.util.List;


/**
 * Response
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-08-25T16:18:19.244-04:00")
public class Response   {
  @SerializedName("custom_fields_names")
  private List<CustomFieldsNames> customFieldsNames = new ArrayList<CustomFieldsNames>();

  @SerializedName("type")
  private String type = null;

  @SerializedName("color_class")
  private String colorClass = null;

  @SerializedName("url")
  private String url = null;

  @SerializedName("event_id")
  private Integer eventId = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("icon_class")
  private String iconClass = null;

  @SerializedName("id")
  private Integer id = null;

  @SerializedName("page")
  private String page = null;

  @SerializedName("position")
  private Integer position = null;

  @SerializedName("items")
  private List<Items> items = new ArrayList<Items>();

  @SerializedName("config")
  private Config config = null;

  @SerializedName("status")
  private Integer status = null;

  public Response customFieldsNames(List<CustomFieldsNames> customFieldsNames) {
    this.customFieldsNames = customFieldsNames;
    return this;
  }

  public Response addCustomFieldsNamesItem(CustomFieldsNames customFieldsNamesItem) {
    this.customFieldsNames.add(customFieldsNamesItem);
    return this;
  }

   /**
   * Get customFieldsNames
   * @return customFieldsNames
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<CustomFieldsNames> getCustomFieldsNames() {
    return customFieldsNames;
  }

  public void setCustomFieldsNames(List<CustomFieldsNames> customFieldsNames) {
    this.customFieldsNames = customFieldsNames;
  }

  public Response type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public Response colorClass(String colorClass) {
    this.colorClass = colorClass;
    return this;
  }

   /**
   * Get colorClass
   * @return colorClass
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getColorClass() {
    return colorClass;
  }

  public void setColorClass(String colorClass) {
    this.colorClass = colorClass;
  }

  public Response url(String url) {
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public Response eventId(Integer eventId) {
    this.eventId = eventId;
    return this;
  }

   /**
   * Get eventId
   * @return eventId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getEventId() {
    return eventId;
  }

  public void setEventId(Integer eventId) {
    this.eventId = eventId;
  }

  public Response name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Response iconClass(String iconClass) {
    this.iconClass = iconClass;
    return this;
  }

   /**
   * Get iconClass
   * @return iconClass
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getIconClass() {
    return iconClass;
  }

  public void setIconClass(String iconClass) {
    this.iconClass = iconClass;
  }

  public Response id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Response page(String page) {
    this.page = page;
    return this;
  }

   /**
   * Get page
   * @return page
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPage() {
    return page;
  }

  public void setPage(String page) {
    this.page = page;
  }

  public Response position(Integer position) {
    this.position = position;
    return this;
  }

   /**
   * Get position
   * @return position
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getPosition() {
    return position;
  }

  public void setPosition(Integer position) {
    this.position = position;
  }

  public Response items(List<Items> items) {
    this.items = items;
    return this;
  }

  public Response addItemsItem(Items itemsItem) {
    this.items.add(itemsItem);
    return this;
  }

   /**
   * Get items
   * @return items
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Items> getItems() {
    return items;
  }

  public void setItems(List<Items> items) {
    this.items = items;
  }

  public Response config(Config config) {
    this.config = config;
    return this;
  }

   /**
   * Get config
   * @return config
  **/
  @ApiModelProperty(example = "null", value = "")
  public Config getConfig() {
    return config;
  }

  public void setConfig(Config config) {
    this.config = config;
  }

  public Response status(Integer status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getStatus() {
    return status;
  }

  public void setStatus(Integer status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Response response = (Response) o;
    return Objects.equals(this.customFieldsNames, response.customFieldsNames) &&
        Objects.equals(this.type, response.type) &&
        Objects.equals(this.colorClass, response.colorClass) &&
        Objects.equals(this.url, response.url) &&
        Objects.equals(this.eventId, response.eventId) &&
        Objects.equals(this.name, response.name) &&
        Objects.equals(this.iconClass, response.iconClass) &&
        Objects.equals(this.id, response.id) &&
        Objects.equals(this.page, response.page) &&
        Objects.equals(this.position, response.position) &&
        Objects.equals(this.items, response.items) &&
        Objects.equals(this.config, response.config) &&
        Objects.equals(this.status, response.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customFieldsNames, type, colorClass, url, eventId, name, iconClass, id, page, position, items, config, status);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Response {\n");
    
    sb.append("    customFieldsNames: ").append(toIndentedString(customFieldsNames)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    colorClass: ").append(toIndentedString(colorClass)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    eventId: ").append(toIndentedString(eventId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    iconClass: ").append(toIndentedString(iconClass)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    page: ").append(toIndentedString(page)).append("\n");
    sb.append("    position: ").append(toIndentedString(position)).append("\n");
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("    config: ").append(toIndentedString(config)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

