/**
 * eventmobi
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: api-v2
 * Contact: support@cloud-elements.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.CustomFieldsValues;
import java.util.ArrayList;
import java.util.List;


/**
 * SectionsItems
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-08-26T15:51:37.800-04:00")
public class SectionsItems   {
  @SerializedName("website")
  private String website = null;

  @SerializedName("image50")
  private String image50 = null;

  @SerializedName("facebook")
  private String facebook = null;

  @SerializedName("about")
  private String about = null;

  @SerializedName("external_id")
  private String externalId = null;

  @SerializedName("linkedin")
  private String linkedin = null;

  @SerializedName("title")
  private String title = null;

  @SerializedName("url")
  private String url = null;

  @SerializedName("twitter")
  private String twitter = null;

  @SerializedName("image100")
  private String image100 = null;

  @SerializedName("custom_fields_values")
  private List<CustomFieldsValues> customFieldsValues = new ArrayList<CustomFieldsValues>();

  @SerializedName("company_name")
  private String companyName = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("first_name")
  private String firstName = null;

  @SerializedName("threetopics")
  private String threetopics = null;

  @SerializedName("email")
  private String email = null;

  public SectionsItems website(String website) {
    this.website = website;
    return this;
  }

   /**
   * Get website
   * @return website
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getWebsite() {
    return website;
  }

  public void setWebsite(String website) {
    this.website = website;
  }

  public SectionsItems image50(String image50) {
    this.image50 = image50;
    return this;
  }

   /**
   * Get image50
   * @return image50
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getImage50() {
    return image50;
  }

  public void setImage50(String image50) {
    this.image50 = image50;
  }

  public SectionsItems facebook(String facebook) {
    this.facebook = facebook;
    return this;
  }

   /**
   * Get facebook
   * @return facebook
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getFacebook() {
    return facebook;
  }

  public void setFacebook(String facebook) {
    this.facebook = facebook;
  }

  public SectionsItems about(String about) {
    this.about = about;
    return this;
  }

   /**
   * Get about
   * @return about
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getAbout() {
    return about;
  }

  public void setAbout(String about) {
    this.about = about;
  }

  public SectionsItems externalId(String externalId) {
    this.externalId = externalId;
    return this;
  }

   /**
   * Get externalId
   * @return externalId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getExternalId() {
    return externalId;
  }

  public void setExternalId(String externalId) {
    this.externalId = externalId;
  }

  public SectionsItems linkedin(String linkedin) {
    this.linkedin = linkedin;
    return this;
  }

   /**
   * Get linkedin
   * @return linkedin
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getLinkedin() {
    return linkedin;
  }

  public void setLinkedin(String linkedin) {
    this.linkedin = linkedin;
  }

  public SectionsItems title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public SectionsItems url(String url) {
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public SectionsItems twitter(String twitter) {
    this.twitter = twitter;
    return this;
  }

   /**
   * Get twitter
   * @return twitter
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTwitter() {
    return twitter;
  }

  public void setTwitter(String twitter) {
    this.twitter = twitter;
  }

  public SectionsItems image100(String image100) {
    this.image100 = image100;
    return this;
  }

   /**
   * Get image100
   * @return image100
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getImage100() {
    return image100;
  }

  public void setImage100(String image100) {
    this.image100 = image100;
  }

  public SectionsItems customFieldsValues(List<CustomFieldsValues> customFieldsValues) {
    this.customFieldsValues = customFieldsValues;
    return this;
  }

  public SectionsItems addCustomFieldsValuesItem(CustomFieldsValues customFieldsValuesItem) {
    this.customFieldsValues.add(customFieldsValuesItem);
    return this;
  }

   /**
   * Get customFieldsValues
   * @return customFieldsValues
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<CustomFieldsValues> getCustomFieldsValues() {
    return customFieldsValues;
  }

  public void setCustomFieldsValues(List<CustomFieldsValues> customFieldsValues) {
    this.customFieldsValues = customFieldsValues;
  }

  public SectionsItems companyName(String companyName) {
    this.companyName = companyName;
    return this;
  }

   /**
   * Get companyName
   * @return companyName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCompanyName() {
    return companyName;
  }

  public void setCompanyName(String companyName) {
    this.companyName = companyName;
  }

  public SectionsItems id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public SectionsItems firstName(String firstName) {
    this.firstName = firstName;
    return this;
  }

   /**
   * Get firstName
   * @return firstName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getFirstName() {
    return firstName;
  }

  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  public SectionsItems threetopics(String threetopics) {
    this.threetopics = threetopics;
    return this;
  }

   /**
   * Get threetopics
   * @return threetopics
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getThreetopics() {
    return threetopics;
  }

  public void setThreetopics(String threetopics) {
    this.threetopics = threetopics;
  }

  public SectionsItems email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SectionsItems sectionsItems = (SectionsItems) o;
    return Objects.equals(this.website, sectionsItems.website) &&
        Objects.equals(this.image50, sectionsItems.image50) &&
        Objects.equals(this.facebook, sectionsItems.facebook) &&
        Objects.equals(this.about, sectionsItems.about) &&
        Objects.equals(this.externalId, sectionsItems.externalId) &&
        Objects.equals(this.linkedin, sectionsItems.linkedin) &&
        Objects.equals(this.title, sectionsItems.title) &&
        Objects.equals(this.url, sectionsItems.url) &&
        Objects.equals(this.twitter, sectionsItems.twitter) &&
        Objects.equals(this.image100, sectionsItems.image100) &&
        Objects.equals(this.customFieldsValues, sectionsItems.customFieldsValues) &&
        Objects.equals(this.companyName, sectionsItems.companyName) &&
        Objects.equals(this.id, sectionsItems.id) &&
        Objects.equals(this.firstName, sectionsItems.firstName) &&
        Objects.equals(this.threetopics, sectionsItems.threetopics) &&
        Objects.equals(this.email, sectionsItems.email);
  }

  @Override
  public int hashCode() {
    return Objects.hash(website, image50, facebook, about, externalId, linkedin, title, url, twitter, image100, customFieldsValues, companyName, id, firstName, threetopics, email);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SectionsItems {\n");
    
    sb.append("    website: ").append(toIndentedString(website)).append("\n");
    sb.append("    image50: ").append(toIndentedString(image50)).append("\n");
    sb.append("    facebook: ").append(toIndentedString(facebook)).append("\n");
    sb.append("    about: ").append(toIndentedString(about)).append("\n");
    sb.append("    externalId: ").append(toIndentedString(externalId)).append("\n");
    sb.append("    linkedin: ").append(toIndentedString(linkedin)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    twitter: ").append(toIndentedString(twitter)).append("\n");
    sb.append("    image100: ").append(toIndentedString(image100)).append("\n");
    sb.append("    customFieldsValues: ").append(toIndentedString(customFieldsValues)).append("\n");
    sb.append("    companyName: ").append(toIndentedString(companyName)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    threetopics: ").append(toIndentedString(threetopics)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

