/**
 * eventmobi
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: api-v2
 * Contact: support@cloud-elements.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * SectionsListObject
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-08-26T15:51:37.800-04:00")
public class SectionsListObject   {
  @SerializedName("partner_name")
  private String partnerName = null;

  @SerializedName("type")
  private String type = null;

  @SerializedName("color_class")
  private String colorClass = null;

  @SerializedName("url")
  private String url = null;

  @SerializedName("event_id")
  private Integer eventId = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("icon_class")
  private String iconClass = null;

  @SerializedName("id")
  private Integer id = null;

  @SerializedName("page")
  private String page = null;

  @SerializedName("position")
  private Integer position = null;

  @SerializedName("partner_token")
  private String partnerToken = null;

  @SerializedName("show_ads")
  private Boolean showAds = null;

  @SerializedName("status")
  private Integer status = null;

  public SectionsListObject partnerName(String partnerName) {
    this.partnerName = partnerName;
    return this;
  }

   /**
   * Get partnerName
   * @return partnerName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPartnerName() {
    return partnerName;
  }

  public void setPartnerName(String partnerName) {
    this.partnerName = partnerName;
  }

  public SectionsListObject type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public SectionsListObject colorClass(String colorClass) {
    this.colorClass = colorClass;
    return this;
  }

   /**
   * Get colorClass
   * @return colorClass
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getColorClass() {
    return colorClass;
  }

  public void setColorClass(String colorClass) {
    this.colorClass = colorClass;
  }

  public SectionsListObject url(String url) {
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public SectionsListObject eventId(Integer eventId) {
    this.eventId = eventId;
    return this;
  }

   /**
   * Get eventId
   * @return eventId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getEventId() {
    return eventId;
  }

  public void setEventId(Integer eventId) {
    this.eventId = eventId;
  }

  public SectionsListObject name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public SectionsListObject iconClass(String iconClass) {
    this.iconClass = iconClass;
    return this;
  }

   /**
   * Get iconClass
   * @return iconClass
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getIconClass() {
    return iconClass;
  }

  public void setIconClass(String iconClass) {
    this.iconClass = iconClass;
  }

  public SectionsListObject id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public SectionsListObject page(String page) {
    this.page = page;
    return this;
  }

   /**
   * Get page
   * @return page
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPage() {
    return page;
  }

  public void setPage(String page) {
    this.page = page;
  }

  public SectionsListObject position(Integer position) {
    this.position = position;
    return this;
  }

   /**
   * Get position
   * @return position
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getPosition() {
    return position;
  }

  public void setPosition(Integer position) {
    this.position = position;
  }

  public SectionsListObject partnerToken(String partnerToken) {
    this.partnerToken = partnerToken;
    return this;
  }

   /**
   * Get partnerToken
   * @return partnerToken
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPartnerToken() {
    return partnerToken;
  }

  public void setPartnerToken(String partnerToken) {
    this.partnerToken = partnerToken;
  }

  public SectionsListObject showAds(Boolean showAds) {
    this.showAds = showAds;
    return this;
  }

   /**
   * Get showAds
   * @return showAds
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getShowAds() {
    return showAds;
  }

  public void setShowAds(Boolean showAds) {
    this.showAds = showAds;
  }

  public SectionsListObject status(Integer status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getStatus() {
    return status;
  }

  public void setStatus(Integer status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SectionsListObject sectionsListObject = (SectionsListObject) o;
    return Objects.equals(this.partnerName, sectionsListObject.partnerName) &&
        Objects.equals(this.type, sectionsListObject.type) &&
        Objects.equals(this.colorClass, sectionsListObject.colorClass) &&
        Objects.equals(this.url, sectionsListObject.url) &&
        Objects.equals(this.eventId, sectionsListObject.eventId) &&
        Objects.equals(this.name, sectionsListObject.name) &&
        Objects.equals(this.iconClass, sectionsListObject.iconClass) &&
        Objects.equals(this.id, sectionsListObject.id) &&
        Objects.equals(this.page, sectionsListObject.page) &&
        Objects.equals(this.position, sectionsListObject.position) &&
        Objects.equals(this.partnerToken, sectionsListObject.partnerToken) &&
        Objects.equals(this.showAds, sectionsListObject.showAds) &&
        Objects.equals(this.status, sectionsListObject.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(partnerName, type, colorClass, url, eventId, name, iconClass, id, page, position, partnerToken, showAds, status);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SectionsListObject {\n");
    
    sb.append("    partnerName: ").append(toIndentedString(partnerName)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    colorClass: ").append(toIndentedString(colorClass)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    eventId: ").append(toIndentedString(eventId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    iconClass: ").append(toIndentedString(iconClass)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    page: ").append(toIndentedString(page)).append("\n");
    sb.append("    position: ").append(toIndentedString(position)).append("\n");
    sb.append("    partnerToken: ").append(toIndentedString(partnerToken)).append("\n");
    sb.append("    showAds: ").append(toIndentedString(showAds)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

