/**
 * eventmobi
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: api-v2
 * Contact: support@cloud-elements.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Eventmobi) {
      root.Eventmobi = {};
    }
    root.Eventmobi.Ads = factory(root.Eventmobi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Ads model module.
   * @module model/Ads
   * @version api-v2
   */

  /**
   * Constructs a new <code>Ads</code>.
   * @alias module:model/Ads
   * @class
   */
  var exports = function() {
    var _this = this;
















  };

  /**
   * Constructs a <code>Ads</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Ads} obj Optional instance to populate.
   * @return {module:model/Ads} The populated <code>Ads</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('sponsorshiplevel')) {
        obj['sponsorshiplevel'] = ApiClient.convertToType(data['sponsorshiplevel'], 'String');
      }
      if (data.hasOwnProperty('logo_name')) {
        obj['logo_name'] = ApiClient.convertToType(data['logo_name'], 'String');
      }
      if (data.hasOwnProperty('call_to_action')) {
        obj['call_to_action'] = ApiClient.convertToType(data['call_to_action'], 'String');
      }
      if (data.hasOwnProperty('exhibitor_id')) {
        obj['exhibitor_id'] = ApiClient.convertToType(data['exhibitor_id'], 'String');
      }
      if (data.hasOwnProperty('link')) {
        obj['link'] = ApiClient.convertToType(data['link'], 'String');
      }
      if (data.hasOwnProperty('rich')) {
        obj['rich'] = ApiClient.convertToType(data['rich'], 'String');
      }
      if (data.hasOwnProperty('exhibitor_name')) {
        obj['exhibitor_name'] = ApiClient.convertToType(data['exhibitor_name'], 'String');
      }
      if (data.hasOwnProperty('title')) {
        obj['title'] = ApiClient.convertToType(data['title'], 'String');
      }
      if (data.hasOwnProperty('message')) {
        obj['message'] = ApiClient.convertToType(data['message'], 'String');
      }
      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
      if (data.hasOwnProperty('call_to_action_url')) {
        obj['call_to_action_url'] = ApiClient.convertToType(data['call_to_action_url'], 'String');
      }
      if (data.hasOwnProperty('filename')) {
        obj['filename'] = ApiClient.convertToType(data['filename'], 'String');
      }
      if (data.hasOwnProperty('background_color')) {
        obj['background_color'] = ApiClient.convertToType(data['background_color'], 'String');
      }
      if (data.hasOwnProperty('call_to_action_text')) {
        obj['call_to_action_text'] = ApiClient.convertToType(data['call_to_action_text'], 'String');
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} sponsorshiplevel
   */
  exports.prototype['sponsorshiplevel'] = undefined;
  /**
   * @member {String} logo_name
   */
  exports.prototype['logo_name'] = undefined;
  /**
   * @member {String} call_to_action
   */
  exports.prototype['call_to_action'] = undefined;
  /**
   * @member {String} exhibitor_id
   */
  exports.prototype['exhibitor_id'] = undefined;
  /**
   * @member {String} link
   */
  exports.prototype['link'] = undefined;
  /**
   * @member {String} rich
   */
  exports.prototype['rich'] = undefined;
  /**
   * @member {String} exhibitor_name
   */
  exports.prototype['exhibitor_name'] = undefined;
  /**
   * @member {String} title
   */
  exports.prototype['title'] = undefined;
  /**
   * @member {String} message
   */
  exports.prototype['message'] = undefined;
  /**
   * @member {String} type
   */
  exports.prototype['type'] = undefined;
  /**
   * @member {String} call_to_action_url
   */
  exports.prototype['call_to_action_url'] = undefined;
  /**
   * @member {String} filename
   */
  exports.prototype['filename'] = undefined;
  /**
   * @member {String} background_color
   */
  exports.prototype['background_color'] = undefined;
  /**
   * @member {String} call_to_action_text
   */
  exports.prototype['call_to_action_text'] = undefined;
  /**
   * @member {String} id
   */
  exports.prototype['id'] = undefined;



  return exports;
}));


