/**
 * eventmobi
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: api-v2
 * Contact: support@cloud-elements.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Eventmobi) {
      root.Eventmobi = {};
    }
    root.Eventmobi.CustomFieldsNames = factory(root.Eventmobi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The CustomFieldsNames model module.
   * @module model/CustomFieldsNames
   * @version api-v2
   */

  /**
   * Constructs a new <code>CustomFieldsNames</code>.
   * @alias module:model/CustomFieldsNames
   * @class
   */
  var exports = function() {
    var _this = this;












  };

  /**
   * Constructs a <code>CustomFieldsNames</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CustomFieldsNames} obj Optional instance to populate.
   * @return {module:model/CustomFieldsNames} The populated <code>CustomFieldsNames</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('type_name')) {
        obj['type_name'] = ApiClient.convertToType(data['type_name'], 'String');
      }
      if (data.hasOwnProperty('event_id')) {
        obj['event_id'] = ApiClient.convertToType(data['event_id'], 'String');
      }
      if (data.hasOwnProperty('deleted')) {
        obj['deleted'] = ApiClient.convertToType(data['deleted'], 'String');
      }
      if (data.hasOwnProperty('section_id')) {
        obj['section_id'] = ApiClient.convertToType(data['section_id'], 'String');
      }
      if (data.hasOwnProperty('visibility')) {
        obj['visibility'] = ApiClient.convertToType(data['visibility'], 'String');
      }
      if (data.hasOwnProperty('type_id')) {
        obj['type_id'] = ApiClient.convertToType(data['type_id'], 'String');
      }
      if (data.hasOwnProperty('edit_permissions')) {
        obj['edit_permissions'] = ApiClient.convertToType(data['edit_permissions'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('position')) {
        obj['position'] = ApiClient.convertToType(data['position'], 'String');
      }
      if (data.hasOwnProperty('validation_id')) {
        obj['validation_id'] = ApiClient.convertToType(data['validation_id'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} type_name
   */
  exports.prototype['type_name'] = undefined;
  /**
   * @member {String} event_id
   */
  exports.prototype['event_id'] = undefined;
  /**
   * @member {String} deleted
   */
  exports.prototype['deleted'] = undefined;
  /**
   * @member {String} section_id
   */
  exports.prototype['section_id'] = undefined;
  /**
   * @member {String} visibility
   */
  exports.prototype['visibility'] = undefined;
  /**
   * @member {String} type_id
   */
  exports.prototype['type_id'] = undefined;
  /**
   * @member {String} edit_permissions
   */
  exports.prototype['edit_permissions'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} position
   */
  exports.prototype['position'] = undefined;
  /**
   * @member {String} validation_id
   */
  exports.prototype['validation_id'] = undefined;



  return exports;
}));


