/**
 * eventmobi
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: api-v2
 * Contact: support@cloud-elements.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Eventmobi) {
      root.Eventmobi = {};
    }
    root.Eventmobi.ObjectsMetadataFields = factory(root.Eventmobi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ObjectsMetadataFields model module.
   * @module model/ObjectsMetadataFields
   * @version api-v2
   */

  /**
   * Constructs a new <code>ObjectsMetadataFields</code>.
   * @alias module:model/ObjectsMetadataFields
   * @class
   */
  var exports = function() {
    var _this = this;







  };

  /**
   * Constructs a <code>ObjectsMetadataFields</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ObjectsMetadataFields} obj Optional instance to populate.
   * @return {module:model/ObjectsMetadataFields} The populated <code>ObjectsMetadataFields</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('mask')) {
        obj['mask'] = ApiClient.convertToType(data['mask'], 'String');
      }
      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
      if (data.hasOwnProperty('vendorDisplayName')) {
        obj['vendorDisplayName'] = ApiClient.convertToType(data['vendorDisplayName'], 'String');
      }
      if (data.hasOwnProperty('vendorPath')) {
        obj['vendorPath'] = ApiClient.convertToType(data['vendorPath'], 'String');
      }
      if (data.hasOwnProperty('vendorReadOnly')) {
        obj['vendorReadOnly'] = ApiClient.convertToType(data['vendorReadOnly'], 'Boolean');
      }
      if (data.hasOwnProperty('vendorRequired')) {
        obj['vendorRequired'] = ApiClient.convertToType(data['vendorRequired'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * @member {String} mask
   */
  exports.prototype['mask'] = undefined;
  /**
   * @member {String} type
   */
  exports.prototype['type'] = undefined;
  /**
   * @member {String} vendorDisplayName
   */
  exports.prototype['vendorDisplayName'] = undefined;
  /**
   * @member {String} vendorPath
   */
  exports.prototype['vendorPath'] = undefined;
  /**
   * @member {Boolean} vendorReadOnly
   */
  exports.prototype['vendorReadOnly'] = undefined;
  /**
   * @member {Boolean} vendorRequired
   */
  exports.prototype['vendorRequired'] = undefined;



  return exports;
}));


