/**
 * eventmobi
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: api-v2
 * Contact: support@cloud-elements.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Eventmobi) {
      root.Eventmobi = {};
    }
    root.Eventmobi.SectionsListObject = factory(root.Eventmobi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The SectionsListObject model module.
   * @module model/SectionsListObject
   * @version api-v2
   */

  /**
   * Constructs a new <code>SectionsListObject</code>.
   * @alias module:model/SectionsListObject
   * @class
   */
  var exports = function() {
    var _this = this;














  };

  /**
   * Constructs a <code>SectionsListObject</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SectionsListObject} obj Optional instance to populate.
   * @return {module:model/SectionsListObject} The populated <code>SectionsListObject</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('partner_name')) {
        obj['partner_name'] = ApiClient.convertToType(data['partner_name'], 'String');
      }
      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
      if (data.hasOwnProperty('color_class')) {
        obj['color_class'] = ApiClient.convertToType(data['color_class'], 'String');
      }
      if (data.hasOwnProperty('url')) {
        obj['url'] = ApiClient.convertToType(data['url'], 'String');
      }
      if (data.hasOwnProperty('event_id')) {
        obj['event_id'] = ApiClient.convertToType(data['event_id'], 'Integer');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('icon_class')) {
        obj['icon_class'] = ApiClient.convertToType(data['icon_class'], 'String');
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Integer');
      }
      if (data.hasOwnProperty('page')) {
        obj['page'] = ApiClient.convertToType(data['page'], 'String');
      }
      if (data.hasOwnProperty('position')) {
        obj['position'] = ApiClient.convertToType(data['position'], 'Integer');
      }
      if (data.hasOwnProperty('partner_token')) {
        obj['partner_token'] = ApiClient.convertToType(data['partner_token'], 'String');
      }
      if (data.hasOwnProperty('show_ads')) {
        obj['show_ads'] = ApiClient.convertToType(data['show_ads'], 'Boolean');
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'Integer');
      }
    }
    return obj;
  }

  /**
   * @member {String} partner_name
   */
  exports.prototype['partner_name'] = undefined;
  /**
   * @member {String} type
   */
  exports.prototype['type'] = undefined;
  /**
   * @member {String} color_class
   */
  exports.prototype['color_class'] = undefined;
  /**
   * @member {String} url
   */
  exports.prototype['url'] = undefined;
  /**
   * @member {Integer} event_id
   */
  exports.prototype['event_id'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {String} icon_class
   */
  exports.prototype['icon_class'] = undefined;
  /**
   * @member {Integer} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} page
   */
  exports.prototype['page'] = undefined;
  /**
   * @member {Integer} position
   */
  exports.prototype['position'] = undefined;
  /**
   * @member {String} partner_token
   */
  exports.prototype['partner_token'] = undefined;
  /**
   * @member {Boolean} show_ads
   */
  exports.prototype['show_ads'] = undefined;
  /**
   * @member {Integer} status
   */
  exports.prototype['status'] = undefined;



  return exports;
}));


